/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void readingFile(FileReader path) throws IOException {
        BufferedReader reader = new BufferedReader(path);
        try {
            int count = 0;
            while (reader.readLine() != null) {
                if ((!reader.readLine().endsWith(";")) && (!reader.readLine().endsWith("{")) &&
                        (!reader.readLine().endsWith("}")) && (!reader.readLine().contains("if")) &&
                        (!reader.readLine().contains("else"))) {
                    System.out.println("Missing Semicolon at Line: " + ++count);
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("The file was not found");
        }

    }
    public static void main(String[] args) throws IOException {
        FileReader filePath = new FileReader("src/main/resources/gates.js");
        readingFile(filePath);
    }

}
